# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_host_service_manager_module.html#ansible-collections-community-vmware-vmware-host-service-manager-module
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_host_ntp_module.html#ansible-collections-community-vmware-vmware-host-ntp-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
  - name: Start ntpd setting for an ESXi Host
    community.vmware.vmware_host_service_manager:
      hostname: '{{ my_vcenter_hostname }}'
      username: '{{ my_vcenter_username }}'
      password: '{{ my_vcenter_password }}'
      validate_certs: 'false'
      esxi_hostname: '{{ item.hostname }}'
      service_name: ntpd
      state: present
    with_items:
    - {hostname: "{{ 'PHX-ESXi-01.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-02.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-03.vclass.phoenix' }}" } 
    delegate_to: localhost

  - name: Set NTP servers for an ESXi Host
    community.vmware.vmware_host_ntp:
      hostname: '{{ my_vcenter_hostname }}'
      username: '{{ my_vcenter_username }}'
      password: '{{ my_vcenter_password }}'
      validate_certs: 'false'
      esxi_hostname: '{{ item.hostname }}'
      state: present
      ntp_servers:
        - 20.20.20.1
    with_items:
    - {hostname: "{{ 'PHX-ESXi-01.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-02.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-03.vclass.phoenix' }}" } 
    delegate_to: localhost

  - name: Start SSH Service
    community.vmware.vmware_host_service_manager:
      hostname: '{{ my_vcenter_hostname }}'
      username: '{{ my_vcenter_username }}'
      password: '{{ my_vcenter_password }}'
      validate_certs: 'false'
      esxi_hostname: '{{ item.hostname }}'
      service_name: TSM-SSH
      state: start
    with_items:
    - {hostname: "{{ 'PHX-ESXi-01.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-02.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-03.vclass.phoenix' }}" } 
    delegate_to: localhost

  - name: Start Shell
    community.vmware.vmware_host_service_manager:
      hostname: '{{ my_vcenter_hostname }}'
      username: '{{ my_vcenter_username }}'
      password: '{{ my_vcenter_password }}'
      validate_certs: 'false'
      esxi_hostname: '{{ item.hostname }}'
      service_name: TSM
      state: start
    with_items:
    - {hostname: "{{ 'PHX-ESXi-01.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-02.vclass.phoenix' }}" }
    - {hostname: "{{ 'PHX-ESXi-03.vclass.phoenix' }}" } 
    delegate_to: localhost

  # - name: Stop ntpd setting for an ESXi Host
  #   community.vmware.vmware_host_service_manager:
  #     hostname: '{{ vcenter_hostname }}'
  #     username: '{{ vcenter_username }}'
  #     password: '{{ vcenter_password }}'
  #     esxi_hostname: '{{ esxi_hostname }}'
  #     service_name: ntpd
  #     state: absent
  #   delegate_to: localhost
