## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_file_operation_module.html#ansible-collections-community-vmware-vmware-guest-file-operation-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html

# k8s-master에 vmware tools 설치하고 root 패스워드 설정까지 하고 돌리기 

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Copy shell script to VM
      community.vmware.vmware_guest_file_operation:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'phoenix'
        vm_password: 'VMware1!'
        copy:
            src: '{{ item.src }}'
            dest: '{{ item.dst }}'
            overwrite: true
      with_items:
      - {src: "/mnt/c/Material/set_net_k8s.yml", dst: "/home/phoenix/set_net.yml" }
      - {src: "/mnt/c/Material/set_k8s_master_vm.sh", dst: "/home/phoenix/setting.sh" }
      - {src: "/mnt/c/Material/install_docker.sh", dst: "/home/phoenix/install_docker.sh" }
      - {src: "/mnt/c/Material/install_k8s.sh", dst: "/home/phoenix/install_k8s.sh" }
      delegate_to: localhost

    - name: Execute shell script on ESXi host
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/bash
        vm_shell_args: "/home/phoenix/setting.sh"
        wait_for_process: True
        timeout: 300
      delegate_to: localhost

    - name: Execute shell script on k8s_master
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/bash
        vm_shell_args: '{{ item.cmd }}'
        wait_for_process: True
        timeout: 120
      with_items:
      - {cmd: "/home/phoenix/install_docker.sh" }
      - {cmd: "/home/phoenix/install_k8s.sh" }
      delegate_to: localhost

    - name: Delete copied shell script
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/rm
        vm_shell_args: '{{ item.cmd }}' 
        wait_for_process: True
      with_items:
      - {cmd: "-rf /home/phoenix/setting.sh" }
      - {cmd: "-rf /home/phoenix/set_net.yml" }
      - {cmd: "-rf /home/phoenix/install_docker.sh" }
      - {cmd: "-rf /home/phoenix/install_k8s.sh" }
      delegate_to: localhost
