## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_file_operation_module.html#ansible-collections-community-vmware-vmware-guest-file-operation-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Copy shell script to VM
      community.vmware.vmware_guest_file_operation:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: '{{ item.vm }}'
        vm_id_type: vm_name
        vm_username: 'phoenix'
        vm_password: 'VMware1!'
        copy:
            src: "/mnt/c/Material/set_k8s_worker.sh"
            dest: "/home/phoenix/join_k8s.sh"
            overwrite: true
      with_items:
      - {vm: "k8s-worker-01" }
      - {vm: "k8s-worker-02" }
      - {vm: "k8s-worker-03" }
      delegate_to: localhost

    - name: Execute shell script on ESXi host
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: '{{ item.vm }}'
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/bash
        vm_shell_args: "/home/phoenix/join_k8s.sh"
        wait_for_process: True
        timeout: 180
      with_items:
      - {vm: "k8s-worker-01" }
      - {vm: "k8s-worker-02" }
      - {vm: "k8s-worker-03" }
      delegate_to: localhost

    - name: Delete copied shell script
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: '{{ item.vm }}'
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/rm
        vm_shell_args: "-rf /home/phoenix/join_k8s.sh"
        wait_for_process: True
      with_items:
      - {vm: "k8s-worker-01" }
      - {vm: "k8s-worker-02" }
      - {vm: "k8s-worker-03" }
      delegate_to: localhost
