## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_file_operation_module.html#ansible-collections-community-vmware-vmware-guest-file-operation-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Copy shell script to VM
      community.vmware.vmware_guest_file_operation:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        copy:
            src: "/mnt/c/Material/create_k8s_token.sh"
            dest: "/home/phoenix/create_token.sh"
            overwrite: true
      delegate_to: localhost

    - name: Execute shell script on k8s vm
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/bash
        vm_shell_args: "/home/phoenix/create_token.sh"
        wait_for_process: True
        timeout: 300
      delegate_to: localhost

    - name: Delete copied shell script
      community.vmware.vmware_vm_shell:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: 'false'
        vm_id: "k8s-master"
        vm_id_type: vm_name
        vm_username: 'root'
        vm_password: 'VMware1!'
        vm_shell: /usr/bin/rm
        vm_shell_args: "-rf /home/phoenix/create_token.sh"
        wait_for_process: True
      delegate_to: localhost
